/**
 * Executable verification metadata. The equation registry is annotated
 * from this contract list; tests are generated from it.
 */

import { attachVerification, listEquations } from "../core/registry.js";
import { oracles } from "./oracles.js";

export const DEFAULT_SEED = 20261004;
export const DEFAULT_CASES = Number(process.env.J2G_PROPERTY_CASES || 1000);

export const CONTRACTS = [
  {
    id: "M_GRAVITY_001",
    name: "Gravity torque",
    implementation: "gravityTorque",
    output: "N*m",
    domain: { mass: ">= 0", g: ">= 0", Lcg: ">= 0" },
    boundaryRules: { mass0: "tau=0", Lcg0: "tau=0", negativeMass: "FAIL", negativeLength: "FAIL" },
    invariants: ["linear in mass", "linear in g", "linear in Lcg"],
    monotonicity: ["mass", "g", "Lcg"],
    scaling: "linear",
    oracle: "m*g*Lcg",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_INERTIA_001",
    name: "Rod inertia",
    implementation: "momentOfInertiaRod",
    output: "kg*m^2",
    domain: { mass: ">= 0", length: "> 0" },
    boundaryRules: { mass0: "I=0", length0: "FAIL", negativeMass: "FAIL" },
    invariants: ["linear in mass", "quadratic in length"],
    oracle: "(1/3)*m*L*L",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_INERTIAL_001",
    name: "Inertial torque",
    implementation: "inertialTorque",
    output: "N*m",
    domain: { inertia: ">= 0", alpha: "finite" },
    boundaryRules: { alpha0: "tau=0", negativeInertia: "FAIL" },
    invariants: ["linear in I", "linear in alpha", "sign follows alpha"],
    oracle: "I*alpha",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_FRICTION_002",
    name: "Proportional friction",
    implementation: "proportionalFriction",
    output: "N*m",
    domain: { kF: ">= 0" },
    boundaryRules: { kF0: "tau=0", negativeKF: "FAIL" },
    invariants: ["linear in kF"],
    oracle: "kF*(tauG+tauI)",
    evidence: "C6",
    status: "S4",
    physicalValidation: "S0",
  },
  {
    id: "M_DYN_002",
    name: "Peak torque",
    implementation: "peakTorqueUniformRod",
    output: "N*m",
    domain: { mass: ">= 0", length: "> 0", alpha: "finite", kF: ">= 0" },
    boundaryRules: { reference: "272.306233333333 N*m" },
    invariants: ["matches independent sum of components"],
    oracle: "tauG+tauI+kF*(tauG+tauI)",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_POWER_001",
    name: "Mechanical power",
    implementation: "mechanicalPower",
    output: "W",
    domain: { tau: "finite", omega: "finite" },
    boundaryRules: { tau0: "P=0", omega0: "P=0" },
    invariants: ["linear in tau", "linear in omega", "sign(P)=sign(tau*omega)"],
    oracle: "tau*omega",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_POWER_002",
    name: "Electrical power",
    implementation: "electricalPower",
    output: "W",
    domain: { eta: "0 < eta <= 1" },
    boundaryRules: { eta0: "FAIL", eta1: "PASS", etaAbove1: "FAIL" },
    oracle: "Pmech/eta",
    evidence: "C3",
    status: "S4",
    physicalValidation: "S0",
  },
  {
    id: "M_TRANS_001",
    name: "Stage reduction",
    implementation: "stageReduction",
    output: "1",
    domain: { teeth: "positive integer", eta: "(0, 1]" },
    boundaryRules: { R1: "omega unchanged", Rdouble: "omega halves, tau doubles at eta=1" },
    oracle: "Nout/Nin",
    evidence: "C3",
    status: "S4",
    physicalValidation: "S0",
  },
  {
    id: "M_CHAIN_001",
    name: "Chain tension",
    implementation: "chainTension",
    output: "N",
    domain: { radius: "> 0" },
    boundaryRules: { radius0: "FAIL" },
    oracle: "tau/r",
    evidence: "C3",
    status: "S4",
    physicalValidation: "S0",
  },
  {
    id: "M_DEFL_001",
    name: "Point-load cantilever",
    implementation: "cantileverPointDeflection",
    output: "m",
    domain: { length: "> 0", E: "> 0", I: "> 0" },
    boundaryRules: { loadCase: "end point load only" },
    oracle: "F*L^3/(3*E*I)",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_DEFL_002",
    name: "Distributed cantilever",
    implementation: "cantileverDistributedDeflection",
    output: "m",
    domain: { length: "> 0" },
    boundaryRules: { loadCase: "uniform load only" },
    oracle: "w*L^4/(8*E*I)",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_SF_001",
    name: "Safety factor",
    implementation: "safetyFactor",
    output: "1",
    domain: { applied: "> 0", allowable: ">= 0" },
    boundaryRules: { atMinimum: "PASS", belowMinimum: "FAIL" },
    oracle: "allowable/applied",
    evidence: "C3",
    status: "S4",
    physicalValidation: "S0",
  },
  {
    id: "M_THERM_002",
    name: "Thermal steady state",
    implementation: "thermalSteady",
    output: "K",
    domain: { Rth: "> 0" },
    boundaryRules: { Rth0: "FAIL", Ploss0: "T=Ta" },
    oracle: "Ta+Ploss*Rth",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_THERM_001",
    name: "Thermal transient",
    implementation: "thermalTransient",
    output: "K",
    domain: { Cth: "> 0", Rth: "> 0", dt: "> 0" },
    boundaryRules: { longTime: "approaches analytical steady state" },
    oracle: "Ta+Ploss*Rth+(T0-Tss)*exp(-t/(Rth*Cth))",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_COST_001",
    name: "Additive cost",
    implementation: "additiveCost",
    output: "currency",
    domain: { components: ">= 0" },
    boundaryRules: { negativeComponent: "FAIL" },
    invariants: ["increasing one component cannot decrease total"],
    oracle: "sum of components",
    evidence: "C3",
    status: "S4",
    physicalValidation: "S0",
  },
  {
    id: "M_SCALE_001",
    name: "Geometric similarity",
    implementation: "scaleFromReference",
    output: "mixed",
    domain: { L: "> 0", Lref: "> 0" },
    boundaryRules: { customGeometry: "exponents not applied" },
    oracle: "m*s^3, tauG*s^4, tauI*s^5",
    evidence: "C3",
    status: "S4",
    physicalValidation: "S0",
  },
  {
    id: "M_INTEGRATION_001",
    name: "Euler",
    implementation: "integrate/euler",
    output: "state",
    domain: { dt: "> 0" },
    boundaryRules: { order: "first-order on dy/dt=y" },
    oracle: "exp(t)",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
  {
    id: "M_INTEGRATION_002",
    name: "RK4",
    implementation: "integrate/rk4",
    output: "state",
    domain: { dt: "> 0" },
    boundaryRules: { order: "fourth-order on dy/dt=y" },
    oracle: "exp(t)",
    evidence: "C3",
    status: "S5",
    physicalValidation: "S0",
  },
];

export function attachContracts() {
  const known = new Set(listEquations().map((eq) => eq.id));
  for (const contract of CONTRACTS) {
    if (known.has(contract.id)) attachVerification(contract.id, contract);
  }
  return CONTRACTS;
}

export { oracles };
